/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.Colaborador;
import Logica.DtColaboracion;
import Logica.DtColaborador;
import Logica.ICategoria;
import Logica.IPropuesta;
import Logica.IUsuario;
import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;

public class Consultar_colaborador extends javax.swing.JInternalFrame {

    private final IPropuesta IP;
    private final ICategoria iCat;
    private final IUsuario iUsu;
    private Colaborador cola;
    DefaultTableModel modeloT;

    public Consultar_colaborador(IPropuesta IP, ICategoria iCat, IUsuario iUsu) {
        modeloT = new DefaultTableModel(null, getColumnas());
        jTa = new JTable(modeloT);
        initComponents();
        this.IP = IP;
        this.iUsu = iUsu;
        this.iCat = iCat;
        List<DtColaborador> listita = iUsu.listarColaboradores();
        DefaultListModel dlm = new DefaultListModel();
        for (int b = 0; b < listita.size(); b++) {
            DtColaborador q = (DtColaborador) listita.get(b);
            String lul = q.getNombre() + "(" + q.getNick() + (")");
            dlm.addElement(lul);
        }

        listCola.setModel(dlm);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCola = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        lblApe1 = new javax.swing.JLabel();
        lblNick1 = new javax.swing.JLabel();
        lblNom1 = new javax.swing.JLabel();
        lblCorreo1 = new javax.swing.JLabel();
        lblFechaN1 = new javax.swing.JLabel();
        lblNick = new javax.swing.JLabel();
        lblNom = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblApe = new javax.swing.JLabel();
        lblFechaN = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTa = new javax.swing.JTable();
        lblImg = new javax.swing.JLabel();
        lblNick2 = new javax.swing.JLabel();
        lblNick3 = new javax.swing.JLabel();
        jCo = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Consulta colaborador");
        setToolTipText("");

        listCola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listColaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listCola);

        lblApe1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblApe1.setText("Apellido:");

        lblNick1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNick1.setText("Nickname:");

        lblNom1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNom1.setText("Nombre:");

        lblCorreo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCorreo1.setText("Correo:");

        lblFechaN1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFechaN1.setText("Fecha de nacimiento");

        lblNick.setText("Nickname");

        lblNom.setText("Nombre");

        lblCorreo.setText("Correo");

        lblApe.setText("Apellido");

        lblFechaN.setText("Fecha de nacimiento:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaN1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblNick1)
                        .addComponent(lblNick, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNom1)
                        .addComponent(lblNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblApe1)
                        .addComponent(lblApe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCorreo1)
                        .addComponent(lblCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblFechaN))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNick1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNick)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNom1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblApe1)
                .addGap(3, 3, 3)
                .addComponent(lblApe)
                .addGap(4, 4, 4)
                .addComponent(lblCorreo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCorreo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFechaN1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFechaN)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTa.setModel(modeloT);
        jTa.setEnabled(false);
        jScrollPane2.setViewportView(jTa);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        lblImg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblNick2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNick2.setText("Imagen:");

        lblNick3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNick3.setText("Filtrar:");

        jCo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNick3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNick2))
                .addGap(57, 57, 57))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblNick3)
                                .addComponent(jCo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(4, 4, 4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNick2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listColaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listColaMouseClicked
        modeloT.setRowCount(0);
        if (listCola.getModel().getSize() != 0) {
            int index = listCola.getSelectedIndex();
            ListModel model = listCola.getModel();
            String f = (String) model.getElementAt(index);
            String[] partes = f.split(Pattern.quote("("));
            String parte1 = partes[0];
            String parte2 = partes[1];
            String[] partes3 = parte2.split(Pattern.quote(")"));
            String parte4 = partes3[0];
            Colaborador p = iUsu.traerColaborador(parte4);
            lblNick.setText(p.getNick());
            lblNom.setText(p.getNombre());
            lblApe.setText(p.getApellido());
            lblCorreo.setText(p.getCorreo());
            SimpleDateFormat sd = new SimpleDateFormat("yyyy-MM-dd");
            String fecha = sd.format(p.getFecha());
            lblFechaN.setText(fecha);
            p.getImg();
            if (p.getImg() == null || p.getImg().equals("")) {
                ImageIcon imgencita = new ImageIcon("Imagenes/icono.jpg");
                Icon iconito = new ImageIcon(imgencita.getImage().getScaledInstance(lblImg.getWidth(), lblImg.getHeight(), Image.SCALE_DEFAULT));
                lblImg.setIcon(iconito);
            } else {
                ImageIcon imagen = new ImageIcon(p.getImg());
                Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lblImg.getWidth(), lblImg.getHeight(), Image.SCALE_DEFAULT));
                lblImg.setIcon(icono);
            }
//        this.nick1 = c.getNick();
            this.pack();
            this.cola = p;

            setFilas(iUsu.traerColaborador(parte4));
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Lista vacia");

        }
    }//GEN-LAST:event_listColaMouseClicked

    private void jCoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCoKeyReleased
        
        listCola.setModel(this.iUsu.BUSCADOR_Colaborador(jCo.getText()));
    }//GEN-LAST:event_jCoKeyReleased
    private String[] getColumnas() {
        String columna[] = new String[]{"Título", "Monto actual", "Proponente", "Estado actual"};
        return columna;
    }

    private void setFilas(Colaborador c) {
        List<DtColaboracion> list = iUsu.datosCol(c);
        for (int i = 0; i < list.size(); i++) {
            modeloT.addRow(new Object[]{list.get(i).getPropuesta().getTitulo(), list.get(i).getPropuesta().getMontoActual(), list.get(i).getPropuesta().getPropo(), list.get(i).getPropuesta().getEstActual().getEstado().toString()});
        }
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jCo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTa;
    private javax.swing.JLabel lblApe;
    private javax.swing.JLabel lblApe1;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblCorreo1;
    private javax.swing.JLabel lblFechaN;
    private javax.swing.JLabel lblFechaN1;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblNick;
    private javax.swing.JLabel lblNick1;
    private javax.swing.JLabel lblNick2;
    private javax.swing.JLabel lblNick3;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblNom1;
    private javax.swing.JList<String> listCola;
    // End of variables declaration//GEN-END:variables
}
