/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.DtColaboracion;
import Logica.DtColaborador;
import Logica.IPropuesta;
import Logica.IUsuario;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author matheo
 */
public class Consulta_colaboracion_a_propuesta extends javax.swing.JInternalFrame {
    private IUsuario IU;
    private IPropuesta IP;
   
    public Consulta_colaboracion_a_propuesta() {
        initComponents();
    }

    public Consulta_colaboracion_a_propuesta(IPropuesta xIP, IUsuario xIU) {
        initComponents();
        this.IP = xIP;
        this.IU = xIU;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        TxtMonto = new javax.swing.JTextField();
        TxtMontoTotal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLColaborador = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        TxtFecha = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtHora = new javax.swing.JTextField();
        TxtBuscarColaborador = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtNick = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtRetorno = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLColaboracion = new javax.swing.JList<>();
        jLabel9 = new javax.swing.JLabel();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel10.setText("Monto recaudado:");

        TxtMonto.setEditable(false);

        TxtMontoTotal.setEditable(false);

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Monto aportado:");

        jLColaborador.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jLColaboradorValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jLColaborador);

        jLabel6.setText("Fecha:");

        TxtFecha.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel1.setText(" Consulta de colaboración a propuesta ");

        jLabel7.setText("Hora:");

        jLabel2.setText("Buscar Colaborador:");

        TxtHora.setEditable(false);

        TxtBuscarColaborador.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtBuscarColaboradorFocusGained(evt);
            }
        });
        TxtBuscarColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBuscarColaboradorActionPerformed(evt);
            }
        });
        TxtBuscarColaborador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtBuscarColaboradorKeyReleased(evt);
            }
        });

        jLabel8.setText("Nick:");

        jLabel3.setText("Colaboradores:");

        TxtNick.setEditable(false);

        jLabel4.setText("Colaboraciones:");

        TxtRetorno.setEditable(false);

        jLColaboracion.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jLColaboracionValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jLColaboracion);

        jLabel9.setText("Retorno:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addContainerGap(83, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtBuscarColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(94, 94, 94))
                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(TxtMontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(TxtNick, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(TxtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(TxtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(17, 17, 17))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TxtBuscarColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtNick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(5, 5, 5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtMontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 34, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jButton1)))
                .addGap(3, 3, 3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLColaboradorValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jLColaboradorValueChanged
        // TODO add your handling code here:
        TxtFecha.setText("");
        TxtHora.setText("");
        TxtMonto.setText("");
        TxtMontoTotal.setText("");
        TxtRetorno.setText("");
        if (jLColaborador.getSelectedIndex() != -1) {
            List<String> colb = IU.SeleccionarColaborante(ObtenerNick(jLColaborador.getSelectedValue()));
            if (colb != null) {
                DefaultListModel modelo = new DefaultListModel();
                for (int i = 0; i < colb.size(); i++) {
                    String p = (String) colb.get(i);
                    modelo.addElement(p);
                }
                jLColaboracion.setModel(modelo);
                TxtNick.setText(ObtenerNick(jLColaborador.getSelectedValue()));
            }

        }
    }//GEN-LAST:event_jLColaboradorValueChanged

    private void TxtBuscarColaboradorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtBuscarColaboradorFocusGained
        // TODO add your handling code here:
        jLColaborador.setSelectedIndex(-1); //PARA QUE NO BUSCQUE SI SELECCIONA LA CAJA ADEMAS LIMPIA
        jLColaboracion.setSelectedIndex(-1);
        jLColaborador.clearSelection();
        jLColaboracion.clearSelection();
        TxtFecha.setText("");
        TxtHora.setText("");
        TxtMonto.setText("");
        TxtMontoTotal.setText("");
        TxtNick.setText("");
        TxtRetorno.setText("");

    }//GEN-LAST:event_TxtBuscarColaboradorFocusGained

    private void TxtBuscarColaboradorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtBuscarColaboradorKeyReleased
        // TODO add your handling code here:
        
        List<DtColaborador> pro = IU.listarColaboradores();
        if (TxtBuscarColaborador.getText().equals("")) { // SI NO BUSCA
            if (!pro.isEmpty()) {
                DefaultListModel modelo = new DefaultListModel();
                for (int i = 0; i < pro.size(); i++) {
                    DtColaborador p = (DtColaborador) pro.get(i);
                    modelo.addElement(p.getNombre()+"("+p.getNick()+")");
                }
                jLColaborador.setModel(modelo);
            }
        } else {                                // SI BUSCA
            if (!pro.isEmpty()) {
                DefaultListModel modelo = new DefaultListModel();
                for (int i = 0; i < pro.size(); i++) {
                    DtColaborador p = (DtColaborador) pro.get(i);
                    if (p.getNombre().contains(TxtBuscarColaborador.getText())) {
                        modelo.addElement(p.getNombre()+"("+p.getNick()+")");
                    }
                }
                jLColaborador.setModel(modelo);
            }
        }
    }//GEN-LAST:event_TxtBuscarColaboradorKeyReleased

    private void jLColaboracionValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jLColaboracionValueChanged
        // TODO add your handling code here:
        if (jLColaboracion.getSelectedIndex() != -1) {
            DtColaboracion x = IU.SeleccionarColaboracion(jLColaboracion.getSelectedValue());
            Date date = x.getFecha();
            DateFormat fecha = new SimpleDateFormat("yyyy/MM/dd");
            String convertido = fecha.format(date);
            TxtFecha.setText(convertido);
            TxtHora.setText(x.getHora());
            TxtMonto.setText(Integer.toString(x.getMonto()));
            TxtMontoTotal.setText(Integer.toString(x.getPropuesta().getMontoActual())); // actual o total??
            TxtRetorno.setText(x.getRetorno().getAmbosRetornos());
        }

    }//GEN-LAST:event_jLColaboracionValueChanged

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
          List<DtColaborador> pro = IU.listarColaboradores();
        if (!pro.isEmpty()) {                                                   // SI HAY PROPUESTAS
            DefaultListModel modelo = new DefaultListModel();                   
            for (int i = 0; i < pro.size(); i++) {
                DtColaborador p = (DtColaborador) pro.get(i);
                modelo.addElement(p.getNombre()+"("+p.getNick()+")");
            }
            jLColaborador.setModel(modelo);
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "No hay Colaborantes");
        }
    }//GEN-LAST:event_formInternalFrameOpened

    private void TxtBuscarColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBuscarColaboradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBuscarColaboradorActionPerformed

     private String ObtenerNick(String nombre) {
        boolean nicksolo = false;
        String nickposta = "";
        for (int a = 0; a < nombre.length(); a++) {
            char xn = nombre.charAt(a);
            if (xn == '(') {
                nicksolo = true;
            }
            if (nicksolo && xn != '(' && xn != ')') {
                nickposta = nickposta+xn;
            }
        };
        return nickposta;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtBuscarColaborador;
    private javax.swing.JTextField TxtFecha;
    private javax.swing.JTextField TxtHora;
    private javax.swing.JTextField TxtMonto;
    private javax.swing.JTextField TxtMontoTotal;
    private javax.swing.JTextField TxtNick;
    private javax.swing.JTextField TxtRetorno;
    private javax.swing.JButton jButton1;
    private javax.swing.JList<String> jLColaboracion;
    private javax.swing.JList<String> jLColaborador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
